//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone_SWP490
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public app_user()
        {
            this.members = new HashSet<member>();
        }
    
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_role { get; set; }
        public string psw { get; set; }
        public string encrypted_psw { get; set; }
        public string full_name { get; set; }
        public string email { get; set; }
        public bool verified { get; set; }
        public bool active { get; set; }
        public string insert_date { get; set; }
        public string update_date { get; set; }
        public Nullable<int> confirm_password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<member> members { get; set; }
    }
}
