//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone_SWP490
{
    using System;
    using System.Collections.Generic;
    
    public partial class contest_member
    {
        public int id { get; set; }
        public int member_id { get; set; }
        public int contest_id { get; set; }
        public Nullable<System.DateTime> check_in_date { get; set; }
        public string note { get; set; }
    
        public virtual contest contest { get; set; }
        public virtual member member { get; set; }
    }
}
