//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone_SWP490
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gocyberx_icpcEntities : DbContext
    {
        public gocyberx_icpcEntities()
            : base("name=gocyberx_icpcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<app_user> app_user { get; set; }
        public virtual DbSet<contest> contests { get; set; }
        public virtual DbSet<contest_member> contest_member { get; set; }
        public virtual DbSet<@event> events { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<member_event> member_event { get; set; }
        public virtual DbSet<page_content> page_content { get; set; }
        public virtual DbSet<school> schools { get; set; }
        public virtual DbSet<documentation> documentations { get; set; }
        public virtual DbSet<image> images { get; set; }
    }
}
