//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone_SWP490
{
    using System;
    using System.Collections.Generic;
    
    public partial class image
    {
        public int user_id { get; set; }
        public string page_id { get; set; }
        public string image_url { get; set; }
        public string alt { get; set; }
        public Nullable<short> position { get; set; }
        public string back_link { get; set; }
    }
}
