//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone_SWP490
{
    using System;
    using System.Collections.Generic;
    
    public partial class page_content
    {
        public int content_id { get; set; }
        public string page_id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public int position { get; set; }
        public string user_role { get; set; }
        public Nullable<int> status { get; set; }
    }
}
