//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone_SWP490
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public int post_id { get; set; }
        public int post_by { get; set; }
        public string insert_date { get; set; }
        public string update_date { get; set; }
        public string title { get; set; }
        public string short_description { get; set; }
        public string content { get; set; }
        public string html_content { get; set; }
        public Nullable<bool> featured { get; set; }
        public Nullable<bool> enabled { get; set; }
        public string schedule_date { get; set; }
        public string post_to { get; set; }
        public string title_image { get; set; }
    }
}
