//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone_SWP490
{
    using System;
    using System.Collections.Generic;
    
    public partial class team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public team()
        {
            this.team_member = new HashSet<team_member>();
        }
    
        public int team_id { get; set; }
        public string team_name { get; set; }
        public Nullable<int> school_id { get; set; }
        public string type { get; set; }
        public Nullable<bool> enabled { get; set; }
        public Nullable<int> contest_id { get; set; }
    
        public virtual school school { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<team_member> team_member { get; set; }
    }
}
